// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieLibrary
{
    public partial class Usertable
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Username cannot be blank")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Invalid user Name.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Password cannot be blank")]

        public string Userpassword { get; set; }
        [EmailAddress(ErrorMessage = "Invalid email address")]
        [Required(ErrorMessage = "Emailid cannot be blank")]
        public string EmailId { get; set; }
        [Range(18, 60, ErrorMessage = "Age should be between 18 to 60")]
        [Required(ErrorMessage = "Age cannot be blank")]
        public int? Age { get; set; }
        [Required(ErrorMessage = "Gender cannot be blank")]

        public bool? Gender { get; set; }
        [RegularExpression("\\d{10}", ErrorMessage = "Pls check the number again")]
        [Required(ErrorMessage = "Phone number cannot be blank")]
        public string PhoneNumber { get; set; }
    }
}