// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieLibrary
{
    public partial class Booking
    {
        public int BookingId { get; set; }
        public int? MovieId { get; set; }
        public string UserName { get; set; }
        public string MovieName { get; set; }
        public DateTime? MovieDate { get; set; }
        public string SeatNo { get; set; }
        public int? NoOfSeats { get; set; }
        public int? Totalprice { get; set; }

        public virtual Movie Movie { get; set; }
    }
}