// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MovieLibrary
{
    public partial class Movie
    {
        public Movie()
        {
            Bookings = new HashSet<Booking>();
        }

        public int MovieId { get; set; }
        [Required(ErrorMessage = "Moviename  should be required")]
        public string MovieName { get; set; }
        [Required(ErrorMessage = "Casthero  should be required")]
        public string Casthero { get; set; }
        [Required(ErrorMessage = "Castheroine  should be required")]
        public string Castheroine { get; set; }
        [Required(ErrorMessage = "Actor1  should be required")]
        public string Castothers1 { get; set; }
        [Required(ErrorMessage = "Actor2  should be required")]
        public string Castothers2 { get; set; }
        [Required(ErrorMessage = "Director  should be required")]
        public string Director { get; set; }
        [Required(ErrorMessage = "Producer  should be required")]
        public string Producer { get; set; }
        [Required(ErrorMessage = "Musician  should be required")]
        public string Musician { get; set; }
        [Required(ErrorMessage = "Genre  should be required")]
        public string Genre { get; set; }
        [Required(ErrorMessage = "catagory  should be required")]
        public string Catagory { get; set; }
        [Required(ErrorMessage = "Movielanguage  should be required")]
        public string Movielanguage { get; set; }
        [Required(ErrorMessage = "Theatername  should be required")]
        public string TheaterName { get; set; }
        [Required(ErrorMessage = "MovieImage  should be required")]
        public string MovieImage { get; set; }
        [Required(ErrorMessage = "MovieDate  should be required")]
        public DateTime? MovieDate { get; set; }
        [Required(ErrorMessage = "MovieDuration  should be required")]
        public string MovieDuration { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }
    }
}